### ISSUE TITLE
Auto-refresh breaks the free-text filter

### ISSUE THREAD

**Issue by 09jvilla** [grafana/traces-drilldown#200]
If you turn on the auto-refresh, as soon as the auto-refresh happens, any filtering you've put in place by typing in a string will no longer be respected. ![Image](https://github.com/user-attachments/assets/55ab961a-eb99-4a5e-943d-b089b3252b24)

Not adding the "obscon" label given the low priority of this bug; at best a 'nice to have' fix before obscon.

https://github.com/user-attachments/assets/3183c0d6-8245-404e-918c-411e31257712

**Comment by joey-grafana** [comment]
Completed in https://github.com/grafana/explore-traces/pull/243
